# Generated by Django 4.2.11 on 2024-03-15 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spottiapp', '0001_initial'),
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='token_type',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ParsedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=255)),
                ('tracks_total', models.IntegerField(default=0)),
                ('url', models.URLField()),
                ('image', models.URLField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spottiapp.post')),
            ],
        ),
    ]
