# Generated by Django 5.0.3 on 2024-03-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spottiapp', '0002_post_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
