# Generated by Django 5.0.3 on 2024-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spottiapp', '0003_rename_user_post_author_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Spottiapp', max_length=100),
        ),
    ]
